name: "test"
clusters:
  cluster-us: 
    nodeSubnet: "172.88.0.0/16"
    podSubnet: "10.196.0.0/16"
    serviceSubnet: "10.96.0.0/16"
  cluster-eu:
    clusterNetwork: 
      nodeSubnet: "172.89.0.0/16"
      podSubnet: "10.197.0.0/16"
      serviceSubnet: "10.97.0.0/16"